name: Deploy site to Github Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-commit:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Check
        uses: ./.github/actions/build

      - name: Move out directory
        run: |
          mkdir -p /tmp/out
          mv ./out/* /tmp/out

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Preserve specific directories
        run: |
          if [ -e ./preview ]; then
            mkdir -p /tmp/preview
            mv ./preview/* /tmp/preview
          fi

      - name: Clean
        run: |
          find . -type f ! -path "./.github/*" ! -path "./.git/*" -delete

      - name: Adapt new build
        run: |
          cp -r -f /tmp/out/* ./
          if [ -e /tmp/preview ]; then
            cp -r -f /tmp/preview/* ./preview
          fi
          touch .nojekyll || true

      - name: Commit changes to gh-pages branch
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add -N .
          set +e
          git diff --exit-code --quiet
          if [[ $? -eq 1 ]]; then
              git add .
              git commit -m "Deploy to gh-pages: ${{ github.sha }}"
              git push origin gh-pages
          fi

      - name: Checkout main branch
        uses: actions/checkout@v4
